### ISSUE TITLE
Getting ArgumentNullException when running

### ISSUE THREAD

**Issue by drmathias** [statiqdev/CleanBlog#4]
Wanted to give this theme a go, so decided to follow the instructions and I'm getting the following error.

> [ERRO] Archives/Process » ForEachDocument » Error while executing module ExecuteConfig in Archives/Process: Value cannot be null. (Parameter 'patterns')
[ERRO] Archives/Process » ForEachDocument » Document [C:/Users/drmathias/repos/ThemedBlog/src/ThemedBlog/input/theme/input/index.cshtml]: Exception of type 'Statiq.Core.ExecuteModulesException' was thrown.
[DBUG] Exception while executing pipeline Archives/Process: System.ArgumentNullException: Value cannot be null. (Parameter 'patterns')
   at Statiq.Core.FilterSources..ctor(IEnumerable`1 patterns)
   at Statiq.Web.Pipelines.Archives.<>c__DisplayClass0_0.<.ctor>b__1(IDocument archiveDoc, IExecutionContext ctx)
   at Statiq.Common.Config.<>c__DisplayClass13_0`1.<FromDocument>b__0(IDocument doc, IExecutionContext ctx)
   at Statiq.Common.Config`1.<>c__DisplayClass10_0.<<op_Implicit>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Statiq.Common.Config`1.GetAndTransformValueAsync(IDocument document, IExecutionContext context, Func`2 transform)
   at Statiq.Common.ParallelConfigModule`1.<>c__DisplayClass8_1.<<ExecuteContextAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Statiq.Common.ParallelAsyncExtensions.ParallelSelectManyAsync[TSource,TResult](IEnumerable`1 items, Func`2 asyncSelector, CancellationToken cancellationToken)
   at Statiq.Common.ParallelConfigModule`1.ExecuteContextAsync(IExecutionContext context)
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Common.Module.ExecuteAsync(IExecutionContext context)
   at Statiq.Core.Engine.ExecuteModulesAsync(ExecutionContextData contextData, IExecutionContext parent, IEnumerable`1 modules, ImmutableArray`1 inputs, ILogger logger)

Steps to reproduce:

1. Follow steps at https://statiq.dev/web/#quick-start
2. `git submodule add https://github.com/statiqdev/CleanBlog.git theme`
3. Created `my-first-post.md` at `input/posts/`

**Comment by daveaglick** [comment]
I think I see the problem, might need to update the instructions to make this clearer: the theme folder should be alongside the input folder (not under it). If you've got the theme folder inside the input folder try moving it out and let me know if that works.

**Comment by drmathias** [comment]
I see, you did write that, just I didn't read it properly. Thanks.
